# no Makefile for lib distribution, commenting everything out ...

#all : lib 
#lib : lib/libphysics.a

#obj/%.o : src/%.c
#	gcc -g -ansi -pedantic -Iinclude -I../common/include -c $< -o $@

#lib/libphysics.a : obj/decay.o obj/projectiles.o obj/sho.o
#	ar -r lib/libphysics.a $^

#clean : 
#	rm -f *.exe *~
#	rm -f src/*.c~
#	rm -f include/*.h~
#	rm -f obj/*.o
#	rm lib/*.a 


#.PHONY : clean 

